/** Driver protocol tests only. Real PostgreSQL is required by verify-account-postgres.mjs. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {PostgresAccountSourceRegistry,ACCOUNT_POSTGRES_SCHEMA} from '../cloud/account-source-postgres.mjs';
import {accountPostgresOptions,accountRegistryKey} from '../cloud/account-postgres-config.mjs';
const tick=1800000000000;
function fixture(overrides={}){
 const calls=[],released=[],key=randomBytes(32);let handler=async()=>({rows:[],rowCount:0}),registry;
 const role={database:'grindzone',role:'grindzone_runtime',rolsuper:false,rolcreatedb:false,rolcreaterole:false,rolbypassrls:false,inherits_roles:false,...overrides};
 let seq=0;
 const pool={query:async()=>assert.fail('Transactions must never use pool.query'),connect:async()=>{const connection=++seq;return {query:async(sql,values)=>{calls.push({connection,sql,values});if(sql.includes('current_database()'))return {rows:[role]};if(sql==='SELECT name,value FROM grindzone.gz_binding_meta')return {rows:[{name:'schema',value:ACCOUNT_POSTGRES_SCHEMA},{name:'key-check',value:registry.tag('key-check',ACCOUNT_POSTGRES_SCHEMA)}]};return handler(sql,values,connection);},release:destroy=>released.push({connection,destroy})};},end:async()=>{}};
 registry=new PostgresAccountSourceRegistry({pool,key,now:()=>tick});const peer={installationId:'test-install',deviceId:'test-device',generation:1,expiresAt:tick+60000};
 return {registry,calls,released,peer,setHandler:fn=>handler=fn};
}
test('dedicated URI produces strict TLS and a bounded pool without inherited PG options',()=>{const o=accountPostgresOptions('postgresql://grindzone_runtime:synthetic@ep-test-pooler.c-10.us-east-1.aws.neon.tech/grindzone?sslmode=require&channel_binding=require');assert.equal(o.ssl.rejectUnauthorized,true);assert.equal(o.max,2);assert.equal(o.user,'grindzone_runtime');assert.equal(o.database,'grindzone');assert.equal(o.connectionString,undefined);assert.equal(o.enableChannelBinding,true);});
for(const bad of ['postgresql://admin:synthetic@ep-test.neon.tech/grindzone?sslmode=require','postgresql://grindzone_runtime:synthetic@ep-test.neon.tech/neondb?sslmode=require','postgresql://grindzone_runtime:synthetic@attacker.test/grindzone?sslmode=require','postgresql://grindzone_runtime:synthetic@ep-test.neon.tech/grindzone?sslmode=disable','postgresql://grindzone_runtime:synthetic@ep-test.neon.tech/grindzone?sslmode=require&options=-csearch_path=public','postgresql://grindzone_runtime:synthetic@ep-test.neon.tech/grindzone?sslmode=require&sslmode=disable'])test('unsafe connection configuration is rejected without echoing credentials: '+bad.split('@').at(-1),()=>assert.throws(()=>accountPostgresOptions(bad),e=>!e.message.includes('synthetic')));
test('registry key is independent and canonical 32-byte base64url',()=>{const key=randomBytes(32);assert.deepEqual(accountRegistryKey(key.toString('base64url')),key);for(const v of [undefined,'password','a'.repeat(42),'!'.repeat(43)])assert.throws(()=>accountRegistryKey(v));});
for(const patch of [{database:'neondb'},{role:'neondb_owner'},{rolsuper:true},{rolbypassrls:true},{rolcreatedb:true},{rolcreaterole:true},{inherits_roles:true}])test('startup rejects unsafe database role '+JSON.stringify(patch),async()=>{const f=fixture(patch);await assert.rejects(f.registry.initialize(),/privileged or unrelated/);assert.equal(f.calls.some(c=>c.sql.includes('gz_binding_meta')),false);assert.equal(f.released.length,1);});
test('all registry transaction statements use one checked-out connection, not pool.query',async()=>{const f=fixture();await f.registry.initialize();await f.registry.observePeer(f.peer);const tx=f.calls.filter(c=>c.connection===2);assert.match(tx[0].sql,/BEGIN/);assert.equal(tx.at(-1).sql,'COMMIT');assert.ok(tx.some(c=>c.sql.includes('pg_advisory_xact_lock')));assert.equal(new Set(tx.map(c=>c.connection)).size,1);assert.equal(f.released.length,2);await f.registry.close();});
test('revoked final transaction guard rolls back and never commits',async()=>{const f=fixture();await f.registry.initialize();let guards=0;await assert.rejects(f.registry.observePeer(f.peer,{authorize:async()=>{if(++guards===2)throw Object.assign(Error('Revoked'),{status:401});}}),e=>e.status===401);assert.equal(f.calls.at(-1).sql,'ROLLBACK');assert.equal(f.calls.filter(c=>c.sql==='COMMIT').length,0);});
test('COMMIT uncertainty is not replayed and destroys the connection',async()=>{const f=fixture();await f.registry.initialize();let commits=0;f.setHandler(async sql=>{if(sql==='COMMIT'){commits++;throw Error('connection lost');}return {rows:[],rowCount:1};});await assert.rejects(f.registry.observePeer(f.peer),e=>e.status===503&&/uncertain/.test(e.message));assert.equal(commits,1);assert.equal(f.released.at(-1).destroy,true);});
test('ROLLBACK failure destroys the connection while preserving authorization denial',async()=>{const f=fixture();await f.registry.initialize();f.setHandler(async sql=>{if(sql==='ROLLBACK')throw Error('closed');return {rows:[],rowCount:1};});await assert.rejects(f.registry.observePeer(f.peer,{authorize:async()=>{throw Object.assign(Error('Revoked'),{status:401});}}),e=>e.status===401);assert.equal(f.released.at(-1).destroy,true);});
test('lock timeout is retryable conflict, not an unrestricted transaction retry',async()=>{const f=fixture();await f.registry.initialize();f.setHandler(async sql=>{if(sql.includes('pg_advisory_xact_lock'))throw Object.assign(Error('lock timeout'),{code:'55P03'});return {rows:[]};});await assert.rejects(f.registry.observePeer(f.peer),e=>e.status===409);assert.equal(f.calls.filter(c=>c.sql.startsWith('BEGIN')).length,1);});
test('PG bigint strings retain exact safe versions and do not leak raw owner tags',async()=>{const f=fixture();await f.registry.initialize();f.setHandler(async sql=>({rows:sql.includes('gz_source_bindings')?[{source_id:'00000000-0000-4000-8000-000000000001',label:'PC',version:'9007199254740991',linked_at:'1800000000000',owner_tag:'secret'}]:[]}));const rows=await f.registry.sources('a'.repeat(64));assert.equal(rows[0].version,Number.MAX_SAFE_INTEGER);assert.equal(rows[0].owner_tag,undefined);});
test('unsafe bigint output is rejected instead of rounded',async()=>{const f=fixture();await f.registry.initialize();f.setHandler(async()=>({rows:[{source_id:'00000000-0000-4000-8000-000000000001',label:'PC',version:'9007199254740992',linked_at:'1'}]}));await assert.rejects(f.registry.sources('a'.repeat(64)),/supported range/);});
test('expired account is checked after acquiring the write lock and before mutations',async()=>{const f=fixture();await f.registry.initialize();await assert.rejects(f.registry.request({owner:'a'.repeat(64),session:'b'.repeat(64),sessionExpires:tick,displayName:'Test'},f.peer,{requestId:'request',label:'PC'}),e=>e.status===401);assert.equal(f.calls.some(c=>/^(INSERT|UPDATE|DELETE)/.test(c.sql)),false);});
test('malformed source IDs never reach a PostgreSQL UUID cast',async()=>{const f=fixture();await f.registry.initialize();await assert.rejects(f.registry.lease('a'.repeat(64),"' OR TRUE --"),e=>e.status===404);assert.equal(f.calls.some(c=>c.sql.includes('WHERE owner_tag=$1 AND source_id=$2')),false);});
test('closed registry refuses operations and key use',async()=>{const f=fixture();await f.registry.initialize();await f.registry.close();await assert.rejects(f.registry.sources('a'.repeat(64)),/not ready/);assert.throws(()=>f.registry.tag('owner','x'),/closed/);});
