import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {createBrowserPlayHandler,browserPlayAssets} from '../cloud/browser-play.mjs';
const response=()=>({headers:null,status:null,body:null,writeHead(status,headers){this.status=status;this.headers=headers},end(body){this.body=body}});
const handler=createBrowserPlayHandler({publicOrigin:'https://example.test/grindzone',readAsset:path=>Buffer.from(path)});
function query(url,options={}){const req={url,method:'GET',headers:{host:'example.test'},...options},res=response();const handled=handler(req,res);return {handled,...res}}
test('no-PC entry serves a page without cookies, pairing or a reader',()=>{const r=query('/grindzone/play/');assert.equal(r.status,200);assert.equal(r.body.toString(),'public/browser-play.html');assert(!r.headers['Set-Cookie']);assert.equal(r.headers['Cache-Control'],'no-store')});
test('public dependency allowlist includes the existing canonical map graph',()=>{for(const file of browserPlayAssets){const r=query('/grindzone/play/'+file);assert.equal(r.status,200);assert.equal(r.body.toString(),'public/'+file)}});
test('catalogs are shared public reference files, not saved player state',()=>{assert.equal(query('/grindzone/play/catalog/maps.json').body.toString(),'lib/maps-data.json');assert.equal(query('/grindzone/play/catalog/reference.json').body.toString(),'lib/rating-data.json')});
test('private or arbitrary file paths are never in the standalone asset list',()=>{for(const path of ['journal.sqlite','lib/store.mjs','account-source-postgres.mjs','catalog/../private.json','secrets.json','api/state'])assert.equal(query('/grindzone/play/'+path).status,404)});
test('the original paired/API routes remain delegated without a new authorization path',()=>{for(const p of ['/grindzone/','/grindzone/phone/pair','/grindzone/api/state','/grindzone/api/command','/grindzone/playback'])assert.equal(query(p).handled,false)});
test('write attempts are rejected without reading or storing their body',()=>{for(const method of ['POST','PUT','PATCH','DELETE']){const r=query('/grindzone/play/',{method});assert.equal(r.status,405)}});
test('wrong host, foreign origin and cross-site embedding are refused',()=>{for(const headers of [{host:'evil.test'},{host:'example.test',origin:'https://evil.test'},{host:'example.test','sec-fetch-site':'cross-site'}])assert.equal(query('/grindzone/play/',{headers}).status,403)});
test('redirect stays inside the fixed mount and HEAD sends no body',()=>{assert.equal(query('/grindzone/play').headers.Location,'/grindzone/play/');assert.equal(query('/grindzone/play/browser-play.js',{method:'HEAD'}).body,'')});
test('asset URL query cannot choose another file or supply a private identity',()=>{assert.equal(query('/grindzone/play/browser-play.js?path=../journal.sqlite&profile=victim').body.toString(),'public/browser-play.js')});
test('insecure non-loopback and arbitrary mounts cannot initialize the handler',()=>{for(const publicOrigin of ['http://example.test/grindzone','https://example.test/other','https://user:secret@example.test/grindzone'])assert.throws(()=>createBrowserPlayHandler({publicOrigin,readAsset:()=>Buffer.alloc(0)}))});
test('real HTTP serves the public page while keeping a protected delegated API protected',async()=>{let origin;const server=http.createServer((req,res)=>{const handler=createBrowserPlayHandler({publicOrigin:origin,readAsset:p=>Buffer.from(p)});if(!handler(req,res)){res.writeHead(401);res.end('Pairing required')}});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port+'/grindzone';try{const page=await fetch(origin+'/play/');assert.equal(page.status,200);assert.equal(await page.text(),'public/browser-play.html');assert.equal((await fetch(origin+'/api/state')).status,401);assert.equal((await fetch(origin+'/play/api/state')).status,404)}finally{await new Promise(r=>server.close(r))}});
