import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {newJournal, validateJournal, applyJournalCommand, commandFingerprint, grindSummary, exportJournal, importJournal, JOURNAL_LIMITS} from '../public/browser-journal.js';
const start = '2026-09-22T04:00:00.000Z', later = '2026-09-22T04:10:00.000Z';
function fixture() { return newJournal({journalId: randomUUID(), platform: 'xbox', now: start}); }
async function run(doc, op, data, now = start, commandId = randomUUID(), expectedRevision = doc.revision) {
 const command = {id: commandId, op, expectedRevision, data};
 return {...applyJournalCommand(doc, command, await commandFingerprint(command), now), command};
}
async function grind() { const journal = fixture(), id = randomUUID(); return (await run(journal, 'grind.start', {grindId: id, name: 'My whitetail grind', targetSpecies: 'Whitetail Deer', reserve: 19})).journal; }
async function report(doc, changes = {}, now = later) {
 return run(doc, 'report.add', {reportId: randomUUID(), grindId: doc.grinds[0].id, version: doc.grinds[0].version, species: 'Whitetail Deer', score: null, medal: 'unknown', sex: 'unknown', points: {}, placeId: null, notes: '', occurredAt: now, ...changes}, now);
}
test('fresh no-PC journal has explicit platform and no invented save data', () => { const d=fixture(); assert.equal(d.platform,'xbox');assert.equal(d.game,'cotw');assert.equal(d.reports.length,0);assert.equal(d.settings.terrain,false);assert(!('career' in d)); });
test('unsupported game, platform and extra identity fields are rejected', () => { for(const bad of [{platform:'console-auto-sync'},{game:'unsupported'},{accountId:'injected'},{profile:'pc'}]) assert.throws(()=>validateJournal({...fixture(),...bad})); });
test('a grind starts with real persisted periods and no harvest count', async()=>{const d=await grind();assert.equal(d.grinds[0].status,'tracking');assert.deepEqual(d.grinds[0].periods,[{startedAt:start,endedAt:null}]);assert.equal(grindSummary(d,d.grinds[0].id).total,0)});
test('cannot start overlapping live grinds', async()=>{const d=await grind();await assert.rejects(()=>run(d,'grind.start',{grindId:randomUUID(),name:'Other',targetSpecies:'Moose',reserve:1}),/Pause or finish/)});
test('pause and resume retain periods rather than resetting the grind', async()=>{let d=await grind(),g=d.grinds[0];d=(await run(d,'grind.pause',{grindId:g.id,version:g.version},later)).journal;assert.equal(d.grinds[0].status,'paused');d=(await run(d,'grind.resume',{grindId:g.id,version:2},'2026-09-22T04:20:00.000Z')).journal;assert.equal(d.grinds[0].periods.length,2);assert.equal(d.grinds[0].periods[0].endedAt,later)});
test('concurrent stale revision or grind version is rejected', async()=>{const d=await grind();await assert.rejects(()=>run(d,'grind.pause',{grindId:d.grinds[0].id,version:1},later,randomUUID(),0),/another tab/);await assert.rejects(()=>run(d,'grind.pause',{grindId:d.grinds[0].id,version:99},later),/grind changed/)});
test('same command is idempotent even after later journal changes', async()=>{let d=await grind();const r=await report(d);d=r.journal;const replay=applyJournalCommand(d,r.command,await commandFingerprint(r.command),later);assert.equal(replay.replay,true);assert.equal(replay.journal.reports.length,1);assert.equal(replay.journal.revision,d.revision)});
test('request identity cannot be reused for another payload', async()=>{const r=await report(await grind());const altered={...r.command,data:{...r.command.data,score:500}};assert.throws(()=>applyJournalCommand(r.journal,altered,'a'.repeat(64),later),/another change/)});
test('target, other, diamond and great-one counts stay distinct and reported', async()=>{let d=await grind();d=(await report(d,{medal:'diamond',score:270})).journal;d=(await report(d,{medal:'great_one',score:400})).journal;d=(await report(d,{species:'North American Beaver'})).journal;const s=grindSummary(d,d.grinds[0].id);assert.deepEqual([s.total,s.target,s.other,s.diamonds,s.greatOnes],[3,2,1,1,1]);assert.equal(s.source,'player_report')});
test('score does not imply a medal and missing values remain unknown', async()=>{const d=(await report(await grind(),{score:999})).journal;assert.equal(d.reports[0].medal,'unknown');assert.equal(grindSummary(d,d.grinds[0].id).diamonds,0)});
test('no report is promoted to a console receipt or auto location', async()=>{const d=(await report(await grind(),{points:{shot:{x:0,z:0}}})).journal;assert.equal(d.reports[0].source,'player_report');assert(!('harvest' in d.reports[0].points));assert(!('death' in d.reports[0].points));await assert.rejects(()=>report(d,{source:'save'}),/Unsupported/)});
test('negative, nonnumeric, infinite or excessive scores fail', async()=>{const d=await grind();for(const score of [-1,'200',NaN,Infinity,1000001]) await assert.rejects(()=>report(d,{score}));});
test('point coordinates must be actual finite numbers; zero is valid', async()=>{const d=await grind();for(const x of [null,'100',NaN,Infinity,100001]) await assert.rejects(()=>report(d,{points:{harvest:{x,z:1}}}));assert.equal((await report(d,{points:{harvest:{x:0,z:0}}})).journal.reports[0].points.harvest.x,0)});
test('future reports and changes after device clock rollback fail', async()=>{const d=await grind();await assert.rejects(()=>report(d,{occurredAt:'2099-01-01T00:00:00.000Z'}),/future/);await assert.rejects(()=>run(d,'settings',{terrain:true},'2026-01-01T00:00:00.000Z'),/clock/)});
test('pause intervals cannot acquire harvests that happened during the break', async()=>{let d=await grind();d=(await run(d,'grind.pause',{grindId:d.grinds[0].id,version:1},later)).journal;await assert.rejects(()=>report(d,{occurredAt:'2026-09-22T04:11:00.000Z'},'2026-09-22T04:20:00.000Z'),/outside/)});
test('locations are explicitly selected and cannot cross reserves', async()=>{let d=await grind();const placeId=randomUUID();d=(await run(d,'place.add',{placeId,name:'Lake',reserve:1,need:'drinking',x:1,z:2})).journal;await assert.rejects(()=>report(d,{placeId}),/not in this reserve/);assert.equal(d.places.length,1)});
test('backup round trip retains identities, timestamps, context and request receipts', async()=>{const d=(await report(await grind(),{points:{shot:{x:10,z:20},death:{x:30,z:40},harvest:{x:50,z:60}}})).journal;assert.deepEqual(importJournal(exportJournal(d)),d)});
test('backup does not accept raw saves, prototype fields or forged automatic sources', async()=>{const d=(await report(await grind())).journal;d.reports[0].source='saved_harvest';assert.throws(()=>validateJournal(d),/Unsupported/);assert.throws(()=>importJournal('{"format":"game-save","version":1}'));assert.throws(()=>importJournal('{"__proto__":{"admin":true}}'));});
test('backup rejects duplicate records and periods with false status', async()=>{const d=(await report(await grind())).journal;const dupe=structuredClone(d);dupe.reports.push({...dupe.reports[0]});assert.throws(()=>validateJournal(dupe),/Duplicate/);const bad=structuredClone(d);bad.grinds[0].status='paused';assert.throws(()=>validateJournal(bad),/period/)});
test('validation and commands do not mutate original records', async()=>{const d=await grind(),before=structuredClone(d);await report(d);validateJournal(d);assert.deepEqual(d,before)});
test('arbitrary text survives as text; control characters are refused', async()=>{const d=await grind();const r=await report(d,{species:'<img src=x onerror=alert(1)>'});assert.equal(r.journal.reports[0].species,'<img src=x onerror=alert(1)>');await assert.rejects(()=>report(d,{species:'deer\nother'}));});
test('finish closes period; continuing explicitly adds another period', async()=>{let d=await grind();d=(await run(d,'grind.finish',{grindId:d.grinds[0].id,version:1},later)).journal;assert.equal(d.grinds[0].status,'finished');d=(await run(d,'grind.resume',{grindId:d.grinds[0].id,version:2},later)).journal;assert.equal(d.grinds[0].periods.length,2)});
test('unknown and privileged commands are refused',async()=>{for(const op of ['save.write','observer.scan','account.bind','__proto__']) await assert.rejects(()=>run(fixture(),op,{}),/not available/)});
test('corrupt or over-capacity backup cannot be silently truncated',()=>{const d=fixture();d.receipts=Array.from({length:JOURNAL_LIMITS.commands+1},()=>({}));assert.throws(()=>validateJournal(d),/size/);assert.throws(()=>importJournal('x'.repeat(JOURNAL_LIMITS.bytes+10001)),/large/)});
