import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeStatistics,careerCounters,buildCareer,statisticsDelta,normalizeProfile} from '../lib/career.mjs';
import {decodeSaveScalars} from '../lib/decoder.mjs';
import {fixture} from './fixtures.mjs';
const value=(n=0)=>({IntValue:n,FloatValue:0,AvgCount:0,AvgValue:0});
const snapshot=(names,values)=>normalizeStatistics({StatsNameHash:names,StatsData:values});
const counter=(s,k)=>careerCounters(s).find(c=>c.key===k)?.value;
test('statistics arrays must have identical lengths',()=>assert.throws(()=>snapshot([1],[])));
test('duplicate identical hash rows are not added together',()=>{const s=snapshot([114106766,114106766],[value(7),value(7)]);assert.equal(counter(s,'shots_hit'),7);assert.equal(s.uniqueRecordCount,1);});
test('conflicting duplicate hash rows are withheld',()=>{const s=snapshot([114106766,114106766],[value(7),value(9)]);assert.equal(counter(s,'shots_hit'),null);assert.deepEqual(s.conflicts,['114106766']);});
test('game-defined shots fired sums hit and missed buckets',()=>{const s=snapshot([114106766,3658525314],[value(7),value(3)]);assert.equal(counter(s,'shots_fired'),10);});
test('missing constituent is unknown, never zero',()=>assert.equal(counter(snapshot([114106766],[value(7)]),'shots_fired'),null));
test('accuracy uses its saved composite independently',()=>{const s=snapshot([4234340396],[{...value(),AvgCount:20,AvgValue:7}]);assert.equal(counter(s,'accuracy'),.35);});
test('zero denominator has no invented accuracy',()=>assert.equal(counter(snapshot([4234340396],[value()]),'accuracy'),null));
test('nonfinite counters fail closed',()=>assert.throws(()=>snapshot([1],[value(Infinity)])));
test('profile normalization excludes unrelated fields',()=>{const s=normalizeProfile({Level:3,Xp:300,Cash:4,SkillPoints:1,PerkPoints:2,TrackingID:'private',Inventory:['private']});assert.equal(s.TrackingID,undefined);assert.deepEqual(Object.keys(s),['level','xp','cash','skillPoints','perkPoints']);});
test('counter changes never infer kills',()=>{const a=snapshot([114106766,3658525314],[value(7),value(3)]),b=snapshot([114106766,3658525314],[value(8),value(3)]);const d=statisticsDelta(a,b);assert.equal(d.killsInferred,0);assert.equal(d.changed.find(c=>c.key==='shots_fired').delta,1);});
test('decreasing career totals flag possible restore',()=>{const a=snapshot([114106766,3658525314],[value(7),value(3)]),b=snapshot([114106766,3658525314],[value(1),value(3)]);assert.equal(statisticsDelta(a,b).resetPossible,true);});
test('all-map views keep unproven attribution unknown',()=>{const c=buildCareer({statistics:{payload:snapshot([114106766,3658525314],[value(7),value(3)])},reserves:[{id:19,name:'Askiy'},{id:14,name:'New England'}],zones:[{reserve:19}],equipment:[],harvests:[],player:{payload:{unharvested:2}}});assert.equal(c.allMaps.length,2);assert.equal(c.lifetimeKills,null);assert.equal(c.unharvested,2);assert.equal(c.allMaps[0].shotsFired,null);assert.equal(c.allMaps[1].zoneCount,0);});
test('scalar projection reads only authorized primitive fields',()=>{const bytes=fixture({root:{NumUnharvestedAnimals:'u32',AnimalHarvestStreak:'u32',TimeOfDay:'f32',PrivateId:'u32'}},'root',{NumUnharvestedAnimals:2,AnimalHarvestStreak:4,TimeOfDay:8,PrivateId:123});const r=decodeSaveScalars(bytes,['NumUnharvestedAnimals','TimeOfDay']);assert.deepEqual(r,{NumUnharvestedAnimals:2,TimeOfDay:8});assert.equal(r.PrivateId,undefined);});
test('scalar projection rejects missing fields',()=>assert.throws(()=>decodeSaveScalars(fixture({root:{Value:'u32'}},'root',{Value:1}),['NoSuchField'])));
test('invalid wrapper cannot enter scalar projection',()=>assert.throws(()=>decodeSaveScalars(Buffer.alloc(80),['TimeOfDay'])));
