import test from 'node:test';
import assert from 'node:assert/strict';
import {createBrowserPlayHandler,ocrVendorAssets} from '../cloud/browser-play.mjs';
function fixture(missing=false){const reads=[];const handle=createBrowserPlayHandler({publicOrigin:'https://example.test/grindzone',readAsset:name=>{reads.push(name);if(missing&&name.includes('/vendor/'))throw Error('not built');return Buffer.from(name);}});return{reads,call(url,method='GET',headers={}){const result={};result.handled=handle({url,method,headers:{host:'example.test',...headers}},{writeHead(status,h){result.status=status;result.headers=h;},end(body){result.body=body;}});return result;}};}
test('every fixed reader asset has its correct type and a same-origin-only worker policy',()=>{const f=fixture();for(const name of ocrVendorAssets){const r=f.call('/grindzone/play/vendor/ocr/'+name);assert.equal(r.status,200);assert.match(r.headers['Content-Security-Policy'],/worker-src 'self'/);assert.doesNotMatch(r.headers['Content-Security-Policy'],/(?:script-src[^;]*'unsafe-eval'|https:\/\/cdn)/);if(name.endsWith('.wasm'))assert.equal(r.headers['Content-Type'],'application/wasm');if(name.endsWith('.gz')){assert.equal(r.headers['Content-Type'],'application/gzip');assert.equal(r.headers['Content-Encoding'],undefined);}}});
test('reader assets cannot accept screenshot or journal uploads',()=>{for(const method of ['POST','PUT','PATCH','DELETE'])assert.equal(fixture().call('/grindzone/play/vendor/ocr/worker.min.js',method).status,405);});
test('reader routing rejects foreign hosts, origins and cross-site requests',()=>{for(const headers of [{host:'evil.test'},{origin:'https://evil.test'},{'sec-fetch-site':'cross-site'},{'sec-fetch-site':'same-site'}])assert.equal(fixture().call('/grindzone/play/vendor/ocr/worker.min.js','GET',headers).status,403);});
test('missing optional reader assets do not prevent opening the existing journal',()=>{const f=fixture(true);assert.equal(f.call('/grindzone/play/').status,200);assert.equal(f.call('/grindzone/play/vendor/ocr/worker.min.js').status,503);assert.equal(f.call('/grindzone/play/browser-journal.js').status,200);});
test('arbitrary vendor paths and encoded traversal never read private files',()=>{const f=fixture(),before=f.reads.length;for(const name of ['../secret','%2e%2e%2fsecret','unknown.js','../../../../api/state']){const r=f.call('/grindzone/play/vendor/ocr/'+name);assert.notEqual(r.status,200);}assert.equal(f.reads.length,before);});
test('HEAD returns no vendor payload and private relay paths are delegated unchanged',()=>{const f=fixture();assert.equal(f.call('/grindzone/play/vendor/ocr/worker.min.js','HEAD').body,'');assert.equal(f.call('/grindzone/api/state').handled,false);assert.equal(f.call('/grindzone/play-other').handled,false);});
