import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createApp} from '../server.mjs';
import {discoveryCatalog,readyDiscoveryReader,writeDiscoveryFixture} from './zone-discovery-fixture.mjs';

test('Hunt state scopes reference zones without changing the legacy phone response',async t=>{
 const root=mkdtempSync(path.join(tmpdir(),'grindzone-hunt-state-')),saveDir=path.join(root,'save');mkdirSync(saveDir);writeDiscoveryFixture(saveDir);
 const app=await createApp({dataDir:path.join(root,'journal'),saveDir,port:0,managedGate:{managed:true,blocked:false,ready(){}}});
 t.after(async()=>{await app.close();rmSync(root,{recursive:true,force:true});});
 const reader=readyDiscoveryReader(discoveryCatalog());app.observer.zoneReference.close();app.observer.zoneReference=reader;
 const profile=app.observer.profile,source=app.observer.source('animal_population_19');
 app.store.saveSource(profile,'animal_population_19',{...source,payload:{...source.payload,populations:[...source.payload.populations,{hash:'45103783',groups:[]}]}});
 app.observer.cache.clear();
 const get=async query=>{const response=await fetch(app.url+'/api/state?reserve=19'+query);return {status:response.status,state:await response.json()};};
 const beforeConsent=await get('&huntSpecies=all');assert.equal(beforeConsent.status,200);
 assert.ok(beforeConsent.state.huntSpeciesOptions.includes('Whitetail Deer'),'a discovered animal remains selectable');
 assert.ok(!beforeConsent.state.huntSpeciesOptions.includes('Mallard'),'population-only species needs spoiler consent');
 assert.equal(reader.calls,0,'default Hunt does not load references before consent');
 app.observer.command({op:'settings',spoilers:true,confirmSpoilers:true});
 const hiddenStop='saved:19:101:0';app.store.set('route:'+profile+':19',[hiddenStop]);
 app.store.set('route-options:'+profile+':19',{mode:'auto',startZoneId:hiddenStop,version:7});
 const before=app.store.db.prepare('SELECT total_changes() AS n').get().n;
 const all=await get('&huntSpecies=all');assert.equal(all.status,200);assert.equal(reader.calls,0,'default Hunt must not even request reference projection');
 assert.equal(all.state.zones.length,1);assert.equal(all.state.zoneActivity.discovery.status,'selection_required');
 assert.ok(all.state.huntSpeciesOptions.includes('Whitetail Deer'));
 assert.ok(all.state.huntSpeciesOptions.includes('Mallard'),'consented population species remains selectable without loading the catalog');
 assert.deepEqual(all.state.route,[hiddenStop]);assert.equal(all.state.routeOptimization.version,7);
 assert.equal(all.state.routeOptimization.status,'scope_limited');assert.equal(all.state.routeOptimization.missingCount,null);
 assert.equal(all.state.zoneHistory.find(row=>row.id===hiddenStop)?.status,'scope_limited');
 assert.equal(all.state.zoneHistory.find(row=>row.id===hiddenStop)?.snapshot,null);
 const chosen=await get('&huntSpecies=Whitetail%20Deer');assert.equal(chosen.status,200);
 assert.equal(chosen.state.zones.filter(z=>z.source==='population_path_reference').length,2);
 assert.equal(chosen.state.routeOptimization.missingCount,0);
 assert.equal(chosen.state.zoneHistory.some(row=>row.id===hiddenStop),false);
 const unrelated=await get('&huntSpecies=Mallard');assert.equal(unrelated.status,200);
 assert.equal(unrelated.state.zones.filter(z=>z.source==='population_path_reference').length,0);
 assert.equal(unrelated.state.routeOptimization.status,'scope_limited');
 assert.equal(unrelated.state.zoneHistory.find(row=>row.id===hiddenStop)?.status,'scope_limited');
 const legacy=await get('');assert.equal(legacy.status,200);
 assert.equal(legacy.state.zones.filter(z=>z.source==='population_path_reference').length,2);
 assert.equal(legacy.state.routeOptimization.missingCount,0);
 assert.equal(legacy.state.zoneHistory.some(row=>row.id===hiddenStop),false);
 assert.equal(Object.hasOwn(legacy.state,'huntSpeciesOptions'),false);
 assert.ok(Buffer.byteLength(JSON.stringify(all.state))<Buffer.byteLength(JSON.stringify(legacy.state)));
 assert.equal((await get('&huntSpecies=all&huntSpecies=Mallard')).status,400);
 assert.equal((await get('&huntSpecies=')).status,400);
 assert.equal(app.store.db.prepare('SELECT total_changes() AS n').get().n,before,'GET requests do not alter the journal');
});
