import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {validBounds,homeBox,tileUrl,tilePlan,insideBounds,scaleBar,zoneMarkerPlan} from '../public/map-geometry.js';
const catalog=JSON.parse(readFileSync(new URL('../lib/maps-data.json',import.meta.url)));
const byId=id=>catalog.reserves.find(r=>r.id===id);
test('full-reserve reference density is bounded without hiding selected, route or discovered zones',()=>{
 const references=Array.from({length:2971},(_,i)=>({id:`reference-${i}`,x:50+i%55*70,z:50+Math.floor(i/55)*70,source:'population_path_reference'}));
 const discovered={id:'discovered',x:150,z:150,source:'save'},offscreen={id:'offscreen',x:10000,z:10000,source:'population_path_reference'};
 const all=[...references,discovered,offscreen],routeIds=new Set(['reference-0']);
 const broad=zoneMarkerPlan(all,[0,0,4000,4000],8,{cluster:true,selectedId:'reference-2970',routeIds});
 assert.equal(broad.visibleCount,2971,'all visible non-route source zones remain accounted for');
 assert.equal(broad.clusters.reduce((count,cluster)=>count+cluster.count,0)+broad.zones.length,2971);
 assert.ok(broad.clusters.length+broad.zones.length<350,'2,971 saved references produce a bounded SVG marker plan');
 assert.ok(broad.zones.some(zone=>zone.id==='reference-2970'),'the selected reference remains individually selectable');
 assert.ok(broad.zones.some(zone=>zone.id==='discovered'),'a discovered zone remains individually selectable');
 assert.ok(!broad.zones.some(zone=>zone.id==='reference-0'),'route stops render in their own numbered layer');
 assert.ok(!broad.zones.some(zone=>zone.id==='offscreen'),'offscreen references are culled');
 const detailed=zoneMarkerPlan(all,[0,0,500,500],1,{cluster:false,routeIds});
 assert.equal(detailed.clusters.length,0,'zooming in reveals the individual references');
 assert.ok(detailed.zones.some(zone=>zone.id==='reference-1'));
 assert.ok(!detailed.zones.some(zone=>zone.id==='offscreen'));
});
test('all 19 reference reserves have real-map geometry',()=>{assert.equal(catalog.reserves.length,19);assert.equal(new Set(catalog.reserves.map(r=>r.id)).size,19);for(const r of catalog.reserves){assert.ok(validBounds(r.bounds));assert.ok(validBounds(r.mapBounds));assert.equal(r.maxZoom,5);assert.ok(r.attribution);assert.match(r.sourcePage,/^https:\/\/mathartbang\.com\/deca\/hp\/map\.html/);}});
test('Askiy source geometry preserves positive X/Z',()=>{const r=byId(19),tiles=tilePlan(r,[12288,8192,2048,2048],256);assert.ok(tiles.length);assert.equal(tiles[0].x,12288);assert.equal(tiles[0].z,8192);assert.match(tiles[0].url,/r19\/t_topo\/3\/6\/4\.png$/);});
test('Hirschfelden keeps negative X rather than an invented zero origin',()=>{const r=byId(0),t=tilePlan(r,[-16384,0,2048,2048],256)[0];assert.equal(t.x,-16384);assert.equal(t.z,0);assert.equal(t.col,0);});
test('Medved keeps negative Z without flipping north and south',()=>{const r=byId(2),t=tilePlan(r,[-16384,-16384,2048,2048],256)[0];assert.equal(t.z,-16384);assert.equal(t.row,0);});
test('Silver Ridge uses its actual shifted image origin',()=>{const r=byId(9),t=tilePlan(r,[-12980,-17156,2048,2048],256)[0];assert.equal(t.x,-12980);assert.equal(t.z,-17156);});
test('tile placement derives width and height independently',()=>{const r={id:19,mapBounds:[[0,0],[8000,4000]],maxZoom:5},t=tilePlan(r,[0,0,4000,2000],256)[0];assert.equal(t.width,4000);assert.equal(t.height,2000);});
test('view outside the image makes no wrapped requests',()=>assert.deepEqual(tilePlan(byId(19),[-2000,-2000,100,100]),[]));
test('tile indices do not include an extra tile at an exact edge',()=>{const t=tilePlan(byId(19),[0,0,2048,2048],256);assert.equal(t.length,1);assert.equal(t[0].col,0);assert.equal(t[0].row,0);});
test('each planned tile retains one correct world-coordinate rectangle',()=>{for(const r of catalog.reserves){const ts=tilePlan(r,homeBox(r),1200);for(const t of ts){assert.equal(t.x,r.mapBounds[0][0]+t.col*t.width);assert.equal(t.z,r.mapBounds[0][1]+t.row*t.height);assert.ok(t.col>=0&&t.row>=0&&t.col<2**t.zoom&&t.row<2**t.zoom);}}});
test('detail resolution increases when zooming in',()=>{const r=byId(19);assert.ok(tilePlan(r,[7000,7000,1000,1000],1000)[0].zoom>tilePlan(r,homeBox(r),1000)[0].zoom);});
test('visible tile planning has a request budget',()=>{for(const r of catalog.reserves)assert.ok(tilePlan(r,homeBox(r),2400,25).length<=25);});
test('tile URL cannot point at arbitrary domains from metadata',()=>assert.equal(tileUrl({...byId(19),tileUrl:'https://attacker.example'},3,2,4),'https://mathartbang.com/deca/hp/data/r19/t_topo/3/2/4.png'));
test('bad tile addresses are rejected',()=>{for(const args of [[-1,0,0],[6,0,0],[3,-1,0],[3,8,0],[3,0,8]])assert.throws(()=>tileUrl(byId(19),...args));});
test('invalid bounds never request fake terrain',()=>{assert.equal(validBounds([[0,0],[0,5]]),false);assert.equal(validBounds([[0,0],[Infinity,5]]),false);assert.deepEqual(tilePlan({id:19,mapBounds:null},[0,0,1,1]),[]);assert.throws(()=>homeBox({bounds:null}));});
test('reference points have names and coordinates, not animal state',()=>{let count=0;for(const r of catalog.reserves)for(const p of r.poi){count++;assert.ok(Number.isFinite(p.x)&&Number.isFinite(p.z));assert.equal(p.source,'public_map_reference');assert.ok(p.label);assert.equal(p.unlocked,undefined);assert.equal(p.Animals,undefined);assert.equal(p.profile,undefined);}assert.equal(count,1615);});
test('Askiy Spoonside reference preserves source coordinates',()=>{const p=byId(19).poi.find(p=>p.label==='Spoonside Rest');assert.equal(p.x,7275.39794921875);assert.equal(p.z,11147.2158203125);});
test('coordinate locate rejects values outside each image',()=>{const r=byId(9);assert.equal(insideBounds(r.mapBounds,-8500,-9000),true);assert.equal(insideBounds(r.mapBounds,50000,50000),false);assert.equal(insideBounds(r.mapBounds,NaN,0),false);});
test('scale bar has positive ground distance and bounded screen length',()=>{const b=scaleBar([0,0,8192,8192],800);assert.ok(b.length>0&&b.pixels<=110);assert.ok(b.label);});
test('public map catalog contains no player-save fields',()=>{const text=JSON.stringify(catalog);for(const marker of ['sourceFolder','HarvestHistory','StatsData','SteamID','playerPosition','journal.sqlite'])assert.ok(!text.includes(marker));});
