import test from 'node:test';
import assert from 'node:assert/strict';
import {buildSaveData} from '../lib/save-data.mjs';
import {projectPhoneState,projectPhoneExport,validatePhoneCommand,PHONE_MAX_BYTES} from '../lib/phone-bridge.mjs';
import {fixture} from './save-data-fixture.mjs';
function state(){const f=fixture();return {...f.state,career:{status:'available',summary:{lifetimeHarvests:109},saveData:buildSaveData(f)},harvestCount:109,harvests:[{id:'receipt',timestamp:123,score:200,species:'Whitetail Deer'}],sessions:[],route:[]}}
test('actual phone projector carries saved-game details without changing harvest totals',()=>{const s=state(),p=projectPhoneState(s);assert.equal(p.career.saveData.equipment.total,2);assert.equal(p.career.saveData.herds.species[0].animals,3);assert.equal(p.harvestCount,109);assert.equal(p.harvests.length,1)});
test('actual phone projector respects current spoiler setting, not a cached rich object',()=>{const s=state();s.settings.spoilers=false;const p=projectPhoneState(s);assert.equal(p.career.saveData.herds.species.length,0);assert.equal(p.harvestCount,109)});
test('actual phone export carries the same allowlisted save summaries',()=>{const s=state();const exported=projectPhoneExport(s);assert.equal(exported.saveData.schema,'grindzone.save-data.v1');assert.equal(exported.saveData.profile.level,42);assert(!JSON.stringify(exported).includes('PRIVATE'))});
test('legacy PC state still projects without a mandatory new field',()=>{const s=state();delete s.career.saveData;const p=projectPhoneState(s);assert(!Object.hasOwn(p.career,'saveData'));assert.equal(p.harvestCount,109)});
test('optional details never force a previously valid near-limit state to fail',()=>{const s=state();s.career.counters=Array.from({length:550},(_,i)=>({key:'counter:'+i,label:'a'.repeat(3600),value:i}));const without={...s,career:{...s.career}};delete without.career.saveData;const base=projectPhoneState(without);assert(Buffer.byteLength(JSON.stringify(base))<PHONE_MAX_BYTES-4096);const p=projectPhoneState(s);assert.equal(p.career.counters.length,550);assert(Buffer.byteLength(JSON.stringify(p))<=PHONE_MAX_BYTES-4096)});
test('save-data feature introduces no remote save-file write command',()=>{assert.throws(()=>validatePhoneCommand({op:'save-data.write',requestId:'abcdefgh',cash:5000}),/not available/);assert.throws(()=>validatePhoneCommand({op:'settings',requestId:'abcdefgh',rawSave:{}}),/Unsupported/)});
test('private nested fields are excluded by the real phone boundary',()=>{const s=state();s.career.saveData.profile.accountToken='SECRET';s.career.saveData.herds.species[0].rawAnimal={identity:'SECRET'};s.career.saveData.equipment.items[0].savePath='SECRET';assert(!JSON.stringify(projectPhoneState(s)).includes('SECRET'))});
