import test from 'node:test';
import assert from 'node:assert/strict';
const listeners={};
const ctx=()=>new Proxy({images:[],measureText:()=>({width:12}),drawImage(...args){this.images.push(args);}}, {get:(v,k)=>k in v?v[k]:()=>{}});
const canvas=()=>{const context=ctx();return {width:1920,height:1080,getContext:()=>context,toBlob:fn=>fn(new Blob(['png'],{type:'image/png'})),context};};
const documentStub={documentElement:{dataset:{runtime:'local'}},addEventListener:(name,handler)=>{listeners[name]=handler;},createElement:()=>canvas()};
globalThis.document=documentStub;
const {ShareStudio,screenshotType,screenshotCrop,openScreenshot}=await import('../public/studio.js');
const png=()=>new File([Uint8Array.from([137,80,78,71,13,10,26,10,0,0,0,0])],'capture.PNG',{type:''});
const root=()=>{const events={},screen=canvas(),message={};return {events,screen,message,addEventListener:(n,h)=>events[n]=h,querySelector:s=>s==='#studioCanvas'?screen:s==='#studioPhotos'?{value:'original'}:null,querySelectorAll:s=>s.includes('studioMessage')?[message]:[]};};
const make=()=>{const r=root(),s=new ShareStudio(r);s.state={};s.design.source='custom';return {s,r};};
const bitmap=()=>({width:3840,height:2160,close(){this.closed=true;}});
for(const [name,bytes,type] of [['png',[137,80,78,71,13,10,26,10],'image/png'],['jpg',[255,216,255,224],'image/jpeg'],['webp',[82,73,70,70,1,0,0,0,87,69,66,80],'image/webp'],['bmp',[66,77,0,0],'image/bmp']])test(name+' screenshot bytes accepted even with absent or misleading MIME',async()=>{
 for(const mime of ['', 'application/octet-stream','image/unknown'])assert.equal(await screenshotType(new File([Uint8Array.from(bytes)],'capture.'+name,{type:mime})),type);
});
test('HTML and SVG do not pass as PNG by extension or MIME',async()=>{for(const bytes of ['<svg></svg>','<script>alert(1)</script>'])await assert.rejects(screenshotType(new File([bytes],'capture.png',{type:'image/png'})),/Use PNG/);});
test('empty input, oversized files and unsupported HDR report actionable errors',async()=>{await assert.rejects(screenshotType(new Blob([])),/empty/);await assert.rejects(screenshotType({size:33*1024*1024,slice(){throw Error('must not read');}}),/32 MB/);await assert.rejects(screenshotType(new Blob(['IIjxr'])),/HDR\/JXR/);});
test('crop anchor stays inside the actual screenshot at all positions',()=>{const image={width:1920,height:1080,studioCrop:{x:0,y:0}};assert.deepEqual(screenshotCrop(image,100,100),[0,0,1080,1080]);image.studioCrop.x=1;assert.deepEqual(screenshotCrop(image,100,100),[840,0,1080,1080]);image.studioCrop.x=999;assert.equal(screenshotCrop(image,100,100)[0],840);image.studioCrop.x=NaN;assert.equal(screenshotCrop(image,100,100)[0],420);});
test('normal screenshot decode retains bounded browser pixels and releases original bitmap',async()=>{const b=bitmap();globalThis.createImageBitmap=async()=>b;const image=await openScreenshot(png());assert.equal(image.width,2560);assert.equal(image.height,1440);assert.equal(b.closed,true);image.close();assert.equal(image.width,0);});
test('overlarge decoded images are released and refused',async()=>{const b=bitmap();b.width=10000;b.height=10000;globalThis.createImageBitmap=async()=>b;await assert.rejects(openScreenshot(png()),/40 megapixels/);assert.equal(b.closed,true);});
test('browser image fallback works without createImageBitmap and revokes its URL',async()=>{
 const priorImage=globalThis.Image,priorCreate=URL.createObjectURL,priorRevoke=URL.revokeObjectURL;let revoked;
 delete globalThis.createImageBitmap;
 globalThis.Image=class {naturalWidth=1920;naturalHeight=1080;set src(v){queueMicrotask(()=>this.onload());}};
 URL.createObjectURL=()=> 'blob:local-test';URL.revokeObjectURL=url=>revoked=url;
 try{const image=await openScreenshot(png());assert.equal(image.width,1920);assert.equal(revoked,'blob:local-test');}finally{globalThis.Image=priorImage;URL.createObjectURL=priorCreate;URL.revokeObjectURL=priorRevoke;}
});
for(const layout of ['stats','trophy','collage','thumbnail'])test(layout+' card actually draws imported screenshot and prepares PNG export',()=>{const {s,r}=make();s.design.layout=layout;s.photos=[canvas()];s.draw();assert.ok(r.screen.context.images.some(call=>call[0]===s.photos[0]));assert.equal(s.currentBlob.type,'image/png');});
test('single-image collage does not insert an empty second-photo tile',()=>{const {s,r}=make();s.design.layout='collage';s.photos=[canvas()];s.draw();assert.equal(r.screen.context.images.length,1);});
test('stats-only card still works without a photo or logged-in account',()=>{const {s,r}=make();s.design.custom='Harvests: 4';s.draw();assert.equal(r.screen.context.images.length,0);assert.ok(s.currentBlob);assert.deepEqual(s.metrics(),[{label:'Harvests',value:'4'}]);});
test('native screenshot picker is before design fields and never forced to camera',()=>{const {s}=make();const html=s.render({});assert.ok(html.indexOf('id="studioPhotos"')<html.indexOf('data-design="layout"'));assert.match(html,/id="studioChoosePhotos" type="button"/);assert.doesNotMatch(html,/capture=/);assert.match(html,/accept="image\/\*,\.png,\.jpg,\.jpeg,\.webp,\.bmp"/);});
test('bad files do not discard valid files from the same batch or blank the card',async()=>{globalThis.createImageBitmap=async()=>bitmap();const {s}=make();await s.addPhotos([new File(['bad'],'bad.png'),png()]);assert.equal(s.photos.length,1);assert.ok(s.currentBlob);assert.match(s.root.message.textContent,/1 screenshot\(s\) added/);assert.match(s.root.message.textContent,/bad.png/);});
test('six-image cap is explicit and never silently replaces existing images',async()=>{globalThis.createImageBitmap=async()=>bitmap();const {s}=make();await s.addPhotos(Array.from({length:7},png));assert.equal(s.photos.length,6);assert.match(s.root.message.textContent,/Only six/);const first=s.photos[0];await s.addPhotos([png()]);assert.equal(s.photos[0],first);assert.match(s.root.message.textContent,/Remove one/);});
test('cancelling the file picker preserves the existing design and image',async()=>{const {s}=make();s.photos=[canvas()];const first=s.photos[0];await s.addPhotos([]);assert.equal(s.photos[0],first);});
test('clear during decoding rejects late images and releases their canvas',async()=>{const {s,r}=make();let finish;globalThis.createImageBitmap=()=>new Promise(resolve=>finish=resolve);const pending=s.addPhotos([png()]);while(!finish)await new Promise(resolve=>setTimeout(resolve,1));r.events.click({target:{closest:selector=>selector==='#studioClearPhotos'?{}:null}});finish(bitmap());await pending;assert.equal(s.photos.length,0);assert.equal(s.busy,false);});
test('pasting over the preview imports the screenshot but normal text paste stays text',async()=>{const {s}=make();let imported,prevented=false;s.addPhotos=async files=>imported=files;listeners.paste({target:{closest:()=>null},clipboardData:{files:[png()],getData:()=>''},preventDefault:()=>prevented=true});assert.equal(imported.length,1);assert.equal(prevented,true);imported=null;listeners.paste({target:{closest:()=>({})},clipboardData:{files:[png()],getData:()=> 'my title'},preventDefault:()=>{throw Error('text paste was blocked');}});assert.equal(imported,null);});
test('late encoded image cannot replace export after a new draw',()=>{const {s,r}=make(),pending=[];r.screen.toBlob=fn=>pending.push(fn);s.draw();s.draw();pending[0](new Blob(['old']));assert.equal(s.currentBlob,null);const current=new Blob(['new']);pending[1](current);assert.equal(s.currentBlob,current);});
test('share passes the prepared image before yielding user activation',async()=>{const {s}=make();s.draw();const prior=Object.getOwnPropertyDescriptor(globalThis,'navigator');let called=false;Object.defineProperty(globalThis,'navigator',{configurable:true,value:{canShare:()=>true,share:({files})=>{called=true;assert.equal(files[0].type,'image/png');return Promise.resolve();}}});try{const result=s.export(true);assert.equal(called,true);await result;}finally{if(prior)Object.defineProperty(globalThis,'navigator',prior);else delete globalThis.navigator;}});
test('crop input redraw does not replace the focused range controls',()=>{const {s}=make();const image=canvas();image.studioCrop={x:.5,y:.5};s.photos=[image];let strip=0;s.renderPhotos=()=>strip++;s.handleDesign({target:{dataset:{photoFocus:'x',photoIndex:'0'},value:'100'}});assert.equal(image.studioCrop.x,1);assert.equal(strip,0);});
